# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

insecure_pub_key = <<~SCRIPT
  set -e
  /usr/bin/wget --no-verbose -c https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
  ls -l vagrant.pub
  ls -l ~/.ssh/authorized_keys
  ls -ld ~/.ssh/
  cat vagrant.pub > ~/.ssh/authorized_keys
  cat ~/.ssh/authorized_keys
  rm -fv vagrant.pub
SCRIPT

Vagrant.configure('2') do |config|
  config.vm.box = 'centos/8'
  config.vbguest.auto_update = false
  config.vm.box_check_update = false

  config.vm.provision 'shell', inline: <<-SHELL
    dnf makecache
    dnf upgrade -y
    dnf install wget -y
  SHELL

  config.vm.provision 'shell',
                      inline: insecure_pub_key,
                      privileged: false
end
