---
- name: managing RPM basic packages
  hosts: all
  become: true
  tasks:
    - name: enable EPEL repository
      dnf:
        name: epel-release
        state: latest
        update_cache: 'yes'
    - name: install required packages
      dnf:
        name:
          - git
          - unzip
          - vim
          - tree
          - nc
          - bind-utils
          - at
          - tmux
          - net-tools
          - wget
          - mailx
    - name: removed unused/unwanted software
      dnf:
        name:
          - kernel-devel.x86_64
          - cpp
          - firewalld
        state: absent
        autoremove: 'yes'
