---
- name: managing RPM basic packages
  hosts: all
  become: true
  tasks:
    - name: enable EPEL repository
      dnf:
        name: epel-release
        state: latest
        update_cache: 'yes'
    - name: install required packages
      dnf:
        name:
          - git
          - unzip
          - vim
          - tree
          - nc
          - bind-utils
          - at
          - tmux
          - net-tools
          - wget
          - mailx
    - name: removed unused/unwanted software
      dnf:
        name:
          - kernel-devel.x86_64
          - cpp
          - firewalld
        state: absent
        autoremove: 'yes'

  # annobin-8.90-1.el8.0.1.x86_64
  # binutils-2.30-73.el8.x86_64
  # cpp-8.3.1-5.el8.0.2.x86_64
  # dwz-0.12-9.el8.x86_64
  # efi-srpm-macros-3-2.el8.noarch
  # elfutils-libelf-devel-0.178-7.el8.x86_64
  # gcc-8.3.1-5.el8.0.2.x86_64
  # ghc-srpm-macros-1.4.2-7.el8.noarch
  # glibc-devel-2.28-101.el8.x86_64
  # glibc-headers-2.28-101.el8.x86_64
  # go-srpm-macros-2-16.el8.noarch
  # isl-0.16.1-6.el8.x86_64
  # kernel-devel-4.18.0-193.6.3.el8_2.x86_64
  # kernel-headers-4.18.0-193.6.3.el8_2.x86_64
  # libmpc-1.0.2-9.el8.x86_64
  # libxcrypt-devel-4.1.1-4.el8.x86_64
  # make-1:4.2.1-10.el8.x86_64
  # ocaml-srpm-macros-5-4.el8.noarch
  # openblas-srpm-macros-2-2.el8.noarch
  # perl-4:5.26.3-416.el8.x86_64
  # perl-Algorithm-Diff-1.1903-9.el8.noarch
  # perl-Archive-Tar-2.30-1.el8.noarch
  # perl-Archive-Zip-1.60-3.el8.noarch
  # perl-Attribute-Handlers-0.99-416.el8.noarch
  # perl-B-Debug-1.26-2.el8.noarch
  # perl-CPAN-2.18-397.el8.noarch
  # perl-CPAN-Meta-2.150010-396.el8.noarch
  # perl-CPAN-Meta-Requirements-2.140-396.el8.noarch
  # perl-CPAN-Meta-YAML-0.018-397.el8.noarch
  # perl-Carp-1.42-396.el8.noarch
  # perl-Compress-Bzip2-2.26-6.el8.x86_64
  # perl-Compress-Raw-Bzip2-2.081-1.el8.x86_64
  # perl-Compress-Raw-Zlib-2.081-1.el8.x86_64
  # perl-Config-Perl-V-0.30-1.el8.noarch
  # perl-DB_File-1.842-1.el8.x86_64
  # perl-Data-Dumper-2.167-399.el8.x86_64
  # perl-Data-OptList-0.110-6.el8.noarch
  # perl-Data-Section-0.200007-3.el8.noarch
  # perl-Devel-PPPort-3.36-5.el8.x86_64
  # perl-Devel-Peek-1.26-416.el8.x86_64
  # perl-Devel-SelfStubber-1.06-416.el8.noarch
  # perl-Devel-Size-0.81-2.el8.x86_64
  # perl-Digest-1.17-395.el8.noarch
  # perl-Digest-MD5-2.55-396.el8.x86_64
  # perl-Digest-SHA-1:6.02-1.el8.x86_64
  # perl-Encode-4:2.97-3.el8.x86_64
  # perl-Encode-Locale-1.05-9.el8.noarch
  # perl-Encode-devel-4:2.97-3.el8.x86_64
  # perl-Env-1.04-395.el8.noarch
  # perl-Errno-1.28-416.el8.x86_64
  # perl-Exporter-5.72-396.el8.noarch
  # perl-ExtUtils-CBuilder-1:0.280230-2.el8.noarch
  # perl-ExtUtils-Command-1:7.34-1.el8.noarch
  # perl-ExtUtils-Embed-1.34-416.el8.noarch
  # perl-ExtUtils-Install-2.14-4.el8.noarch
  # perl-ExtUtils-MM-Utils-1:7.34-1.el8.noarch
  # perl-ExtUtils-MakeMaker-1:7.34-1.el8.noarch
  # perl-ExtUtils-Manifest-1.70-395.el8.noarch
  # perl-ExtUtils-Miniperl-1.06-416.el8.noarch
  # perl-ExtUtils-ParseXS-1:3.35-2.el8.noarch
  # perl-File-Fetch-0.56-2.el8.noarch
  # perl-File-HomeDir-1.002-4.el8.noarch
  # perl-File-Path-2.15-2.el8.noarch
  # perl-File-Temp-0.230.600-1.el8.noarch
  # perl-File-Which-1.22-2.el8.noarch
  # perl-Filter-2:1.58-2.el8.x86_64
  # perl-Filter-Simple-0.94-2.el8.noarch
  # perl-Getopt-Long-1:2.50-4.el8.noarch
  # perl-HTTP-Tiny-0.074-1.el8.noarch
  # perl-IO-1.38-416.el8.x86_64
  # perl-IO-Compress-2.081-1.el8.noarch
  # perl-IO-Socket-IP-0.39-5.el8.noarch
  # perl-IO-Socket-SSL-2.066-4.el8.noarch
  # perl-IO-Zlib-1:1.10-416.el8.noarch
  # perl-IPC-Cmd-2:1.02-1.el8.noarch
  # perl-IPC-SysV-2.07-397.el8.x86_64
  # perl-IPC-System-Simple-1.25-17.el8.noarch
  # perl-JSON-PP-1:2.97.001-3.el8.noarch
  # perl-Locale-Codes-3.57-1.el8.noarch
  # perl-Locale-Maketext-1.28-396.el8.noarch
  # perl-Locale-Maketext-Simple-1:0.21-416.el8.noarch
  # perl-MIME-Base64-3.15-396.el8.x86_64
  # perl-MRO-Compat-0.13-4.el8.noarch
  # perl-Math-BigInt-1:1.9998.11-7.el8.noarch
  # perl-Math-BigInt-FastCalc-0.500.600-6.el8.x86_64
  # perl-Math-BigRat-0.2614-1.el8.noarch
  # perl-Math-Complex-1.59-416.el8.noarch
  # perl-Memoize-1.03-416.el8.noarch
  # perl-Module-Build-2:0.42.24-5.el8.noarch
  # perl-Module-CoreList-1:5.20181130-1.el8.noarch
  # perl-Module-CoreList-tools-1:5.20181130-1.el8.noarch
  # perl-Module-Load-1:0.32-395.el8.noarch
  # perl-Module-Load-Conditional-0.68-395.el8.noarch
  # perl-Module-Loaded-1:0.08-416.el8.noarch
  # perl-Module-Metadata-1.000033-395.el8.noarch
  # perl-Mozilla-CA-20160104-7.el8.noarch
  # perl-Net-Ping-2.55-416.el8.noarch
  # perl-Net-SSLeay-1.88-1.el8.x86_64
  # perl-Package-Generator-1.106-11.el8.noarch
  # perl-Params-Check-1:0.38-395.el8.noarch
  # perl-Params-Util-1.07-22.el8.x86_64
  # perl-PathTools-3.74-1.el8.x86_64
  # perl-Perl-OSType-1.010-396.el8.noarch
  # perl-PerlIO-via-QuotedPrint-0.08-395.el8.noarch
  # perl-Pod-Checker-4:1.73-395.el8.noarch
  # perl-Pod-Escapes-1:1.07-395.el8.noarch
  # perl-Pod-Html-1.22.02-416.el8.noarch
  # perl-Pod-Parser-1.63-396.el8.noarch
  # perl-Pod-Perldoc-3.28-396.el8.noarch
  # perl-Pod-Simple-1:3.35-395.el8.noarch
  # perl-Pod-Usage-4:1.69-395.el8.noarch
  # perl-Scalar-List-Utils-3:1.49-2.el8.x86_64
  # perl-SelfLoader-1.23-416.el8.noarch
  # perl-Socket-4:2.027-3.el8.x86_64
  # perl-Software-License-0.103013-2.el8.noarch
  # perl-Storable-1:3.11-3.el8.x86_64
  # perl-Sub-Exporter-0.987-15.el8.noarch
  # perl-Sub-Install-0.928-14.el8.noarch
  # perl-Sys-Syslog-0.35-397.el8.x86_64
  # perl-Term-ANSIColor-4.06-396.el8.noarch
  # perl-Term-Cap-1.17-395.el8.noarch
  # perl-TermReadKey-2.37-7.el8.x86_64
  # perl-Test-1.30-416.el8.noarch
  # perl-Test-Harness-1:3.42-1.el8.noarch
  # perl-Test-Simple-1:1.302135-1.el8.noarch
  # perl-Text-Balanced-2.03-395.el8.noarch
  # perl-Text-Diff-1.45-2.el8.noarch
  # perl-Text-Glob-0.11-4.el8.noarch
  # perl-Text-ParseWords-3.30-395.el8.noarch
  # perl-Text-Tabs+Wrap-2013.0523-395.el8.noarch
  # perl-Text-Template-1.51-1.el8.noarch
  # perl-Thread-Queue-3.13-1.el8.noarch
  # perl-Time-HiRes-1.9758-1.el8.x86_64
  # perl-Time-Local-1:1.280-1.el8.noarch
  # perl-Time-Piece-1.31-416.el8.x86_64
  # perl-URI-1.73-3.el8.noarch
  # perl-Unicode-Collate-1.25-2.el8.x86_64
  # perl-Unicode-Normalize-1.25-396.el8.x86_64
  # perl-autodie-2.29-396.el8.noarch
  # perl-bignum-0.49-2.el8.noarch
  # perl-constant-1.33-396.el8.noarch
  # perl-devel-4:5.26.3-416.el8.x86_64
  # perl-encoding-4:2.22-3.el8.x86_64
  # perl-experimental-0.019-2.el8.noarch
  # perl-inc-latest-2:0.500-9.el8.noarch
  # perl-interpreter-4:5.26.3-416.el8.x86_64
  # perl-libnet-3.11-3.el8.noarch
  # perl-libnetcfg-4:5.26.3-416.el8.noarch
  # perl-libs-4:5.26.3-416.el8.x86_64
  # perl-local-lib-2.000024-2.el8.noarch
  # perl-macros-4:5.26.3-416.el8.x86_64
  # perl-open-1.11-416.el8.noarch
  # perl-parent-1:0.237-1.el8.noarch
  # perl-perlfaq-5.20180605-1.el8.noarch
  # perl-podlators-4.11-1.el8.noarch
  # perl-srpm-macros-1-25.el8.noarch
  # perl-threads-1:2.21-2.el8.x86_64
  # perl-threads-shared-1.58-2.el8.x86_64
  # perl-utils-5.26.3-416.el8.noarch
  # perl-version-6:0.99.24-1.el8.x86_64
  # python-srpm-macros-3-38.el8.noarch
  # python3-pyparsing-2.1.10-7.el8.noarch
  # python3-rpm-macros-3-38.el8.noarch
  # qt5-srpm-macros-5.12.5-3.el8.noarch
  # redhat-rpm-config-122-1.el8.noarch
  # rust-srpm-macros-5-2.el8.noarch
  # systemtap-sdt-devel-4.2-6.el8.x86_64
  # unzip-6.0-43.el8.x86_64
  # zip-3.0-23.el8.x86_64
  # zlib-devel-1.2.11-13.el8.x86_64 
